.github/workflows/main.yml
name: CI/CD Pipeline

on:
push:
branches:
- main
pull_request:
branches:
- main

jobs:
build_and_test:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: pip install -r GenAI_Factory/requirements.txt

  - name: Run tests
    run: pytest GenAI_Factory/domain_models/genai_assistant/tests/

build_and_push_docker:
needs: build_and_test
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v2

  - name: Log in to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  
  - name: Build and push assistant image
    uses: docker/build-push-action@v2
    with:
      context: .
      file: ./infra/docker/Dockerfile.assistant
      push: true
      tags: your-docker-registry/genai-assistant:latest
